import './globals.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Inter } from 'next/font/google';
import Header from './components/Header';
import Nav from './components/Nav';
// import { Provider } from 'react-redux';
// import store from '@/store/store';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Game Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    // <Provider store={store}> 
    <html lang="en">
      <body
        className={inter.className}
        style={{ display: 'flex', flexFlow: 'column nowrap' }}
      >
        <Header />
        {children}
        <Nav />
      </body>
    </html>
    // </Provider> 
  );
}
